# Generated by Django 5.2.7 on 2025-10-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_activation_key_user_activation_key_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
