# Generated by Django 5.2.7 on 2025-10-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_type', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('coupe', 'Купе'), ('hatchback', 'Хэтчбек'), ('sport', 'Спорткар')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электрический'), ('hybrid', 'Гибрид')], max_length=20)),
                ('engine_volume', models.FloatField()),
                ('power', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
