# Generated by Django 5.2.7 on 2025-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_ad_car_is_active_carimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Рекламное объявление', 'verbose_name_plural': 'Рекламные объявления'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у')], default='used', max_length=10, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='car',
            name='installment',
            field=models.BooleanField(default=True, verbose_name='Рассрочка'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег (км)'),
        ),
        migrations.AddField(
            model_name='car',
            name='phone',
            field=models.CharField(default='+996700727745', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='car',
            name='steering',
            field=models.CharField(choices=[('left', 'Слева'), ('right', 'Справа')], default='left', max_length=10, verbose_name='Руль'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Механическая'), ('automatic', 'Автоматическая'), ('tiptronic', 'Типтроник'), ('robot', 'Роботизированная')], default=1, max_length=20, verbose_name='Коробка передач'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='installment_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфо о рассрочке'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('coupe', 'Купе'), ('hatchback', 'Хэтчбек'), ('sport', 'Спорткар'), ('electric', 'Электромобиль')], max_length=20, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электрический'), ('hybrid', 'Гибрид')], max_length=20, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
